### ISSUE TITLE
Add support for ES6 imports

### ISSUE THREAD

**Issue by ipanasenko** [gkatsev/babel-plugin-inline-json#5]
I think title says it all.
There is [babel-plugin-inline-json-import](https://www.npmjs.com/package/babel-plugin-inline-json-import), but why have two modules when we can have only one?

Also, I think we can do something like this:
```
import {foo} from './config.json';
```

**Comment by gkatsev** [comment]
Yup, would be good to implement. Want to take a crack at it?

**Comment by ipanasenko** [comment]
I can try. Will try tomorrow.
Will need to investigate how named import from json will work together with eslint-plugin-import, which verifies named imports

**Comment by gkatsev** [comment]
Well, this took forever, but someone pinged me about updating this to babel 7, which I did, and the noticed that this issue was still a thing, so, I added a change for it.
